services:

  postgresql:
    image: postgres:latest
    container_name: postgres_auth
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-auth:/data
    networks:
      - network_db


  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    command: [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080" ]
    restart: always
    networks:
      - network_db

volumes:
  db-auth:

networks:
  network_db:
    driver: bridge
