"""
replaced phone number with email 

Revision ID: b8792e0e0fa8
Revises: 3b008a8a74d9
Create Date: 2025-05-08 17:21:59.745996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8792e0e0fa8'
down_revision: Union[str, None] = '3b008a8a74d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint('admins_phone_number_key', 'admins', type_='unique')
    op.create_unique_constraint(None, 'admins', ['email'])
    op.drop_column('admins', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admins', type_='unique')
    op.create_unique_constraint('admins_phone_number_key', 'admins', ['phone_number'])
    op.drop_column('admins', 'email')
    # ### end Alembic commands ###
