"""add user_id

Revision ID: 26b3bda28c13
Revises: 8e3f83828ceb
Create Date: 2025-03-07 19:57:44.496027

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '26b3bda28c13'
down_revision: Union[str, None] = '8e3f83828ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermailrus', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'usermailrus', 'users', ['user_id'], ['id'])
    op.add_column('uservks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'uservks', 'users', ['user_id'], ['id'])
    op.add_column('useryandexs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'useryandexs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'useryandexs', type_='foreignkey')
    op.drop_column('useryandexs', 'user_id')
    op.drop_constraint(None, 'uservks', type_='foreignkey')
    op.drop_column('uservks', 'user_id')
    op.drop_constraint(None, 'usermailrus', type_='foreignkey')
    op.drop_column('usermailrus', 'user_id')
    # ### end Alembic commands ###
