"""add table yandex

Revision ID: ef1fc64fce36
Revises: d185a2c52b2d
Create Date: 2025-01-25 01:34:46.335067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1fc64fce36'
down_revision: Union[str, None] = 'd185a2c52b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useryandexs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_yandex', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_yandex')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useryandexs')
    # ### end Alembic commands ###
